// === LEVELS DEFINITIONS ===
// TODOs 7, 11, and 12 will require changes to this section
const LEVELS = [
  {
    name: "Neon Sprint",
    speed: 2,
    gameObjects: [
      { type: "powerup", kind: "healthUp", x: 320, y: groundY - 60 },
      { type: "platform", kind: "basicPlatform", x: 420, y: groundY - 90 },
      { type: "obstacle", kind: "spikes", x: 560, y: groundY },
      { type: "enemy", kind: "bug", x: 720, y: groundY },
      { type: "platform", kind: "basicPlatform", x: 820, y: groundY - 120 },
      { type: "powerup", kind: "healthUp", x: 980, y: groundY - 80 },
      { type: "obstacle", kind: "spikes", x: 1100, y: groundY },
      { type: "enemy", kind: "bug", x: 1260, y: groundY },
      { type: "platform", kind: "basicPlatform", x: 1380, y: groundY - 150 },
      { type: "platform", kind: "basicPlatform", x: 1600, y: groundY - 90 },
      { type: "obstacle", kind: "spikes", x: 1760, y: groundY },
      { type: "enemy", kind: "bug", x: 1900, y: groundY },
      { type: "platform", kind: "basicPlatform", x: 2050, y: groundY - 120 },
      { type: "goal", kind: "flag", x: 2350, y: groundY },
    ],
  },
  {
    name: "Skyline Rush",
    speed: 3,
    gameObjects: [
      { type: "platform", kind: "basicPlatform", x: 350, y: groundY - 80 },
      { type: "powerup", kind: "healthUp", x: 430, y: groundY - 70 },
      { type: "obstacle", kind: "spikes", x: 620, y: groundY },
      { type: "enemy", kind: "bug", x: 760, y: groundY },
      { type: "platform", kind: "basicPlatform", x: 900, y: groundY - 120 },
      { type: "obstacle", kind: "spikes", x: 1120, y: groundY },
      { type: "enemy", kind: "bug", x: 1260, y: groundY },
      { type: "powerup", kind: "healthUp", x: 1380, y: groundY - 90 },
      { type: "platform", kind: "basicPlatform", x: 1520, y: groundY - 100 },
      { type: "obstacle", kind: "spikes", x: 1680, y: groundY },
      { type: "enemy", kind: "bug", x: 1810, y: groundY },
      { type: "platform", kind: "basicPlatform", x: 1950, y: groundY - 150 },
      { type: "obstacle", kind: "spikes", x: 2160, y: groundY },
      { type: "enemy", kind: "bug", x: 2280, y: groundY },
      { type: "powerup", kind: "healthUp", x: 2440, y: groundY - 80 },
      { type: "platform", kind: "basicPlatform", x: 2580, y: groundY - 90 },
      { type: "goal", kind: "flag", x: 2820, y: groundY },
    ],
  },
  {
    name: "Level 3: Final Circuit",
    speed: 4,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 420, y: groundY },
      { type: "platform", kind: "basicPlatform", x: 540, y: groundY - 60 },
      { type: "enemy", kind: "bug", x: 700, y: groundY },
      { type: "powerup", kind: "healthUp", x: 820, y: groundY - 70 },
      { type: "obstacle", kind: "spikes", x: 980, y: groundY },
      { type: "platform", kind: "basicPlatform", x: 1100, y: groundY - 110 },
      { type: "enemy", kind: "bug", x: 1220, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1380, y: groundY },
      { type: "platform", kind: "basicPlatform", x: 1520, y: groundY - 140 },
      { type: "powerup", kind: "healthUp", x: 1660, y: groundY - 80 },
      { type: "enemy", kind: "bug", x: 1820, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1960, y: groundY },
      { type: "platform", kind: "basicPlatform", x: 2120, y: groundY - 90 },
      { type: "enemy", kind: "bug", x: 2260, y: groundY },
      { type: "powerup", kind: "healthUp", x: 2400, y: groundY - 90 },
      { type: "obstacle", kind: "spikes", x: 2550, y: groundY },
      { type: "platform", kind: "basicPlatform", x: 2700, y: groundY - 120 },
      { type: "enemy", kind: "bug", x: 2870, y: groundY },
      { type: "goal", kind: "flag", x: 3120, y: groundY },
    ],
  },
];

let currentLevel = LEVELS[0];
let currentLevelIndex = 0;
// === END LEVELS DEFINITIONS ===

// === DEFAULT VALUES FOR EACH "type" AND "kind" OF OBJECT (STUDENT-EDITABLE) ===
const DEFAULT_VALUES = {
  obstacle: {
    spikes: {
      imageUrl: "images/interactable/spikes.png",
      width: 48,
      height: 48,
      hitWidth: 40,
      hitHeight: 44,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: -20,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: false,
    },
  },
  enemy: {
    bug: {
      imageUrl: "images/interactable/bug.png",
      width: 75,
      height: 75,
      hitWidth: 75,
      hitHeight: 75,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 75,
      contactHealthChange: -30,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 50,
      hp: 3,
      collect: false,
    },
  },
  powerup: {
    healthUp: {
      imageUrl: "images/interactable/health-up.png",
      width: 32,
      height: 32,
      hitWidth: 32,
      hitHeight: 32,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 32,
      contactHealthChange: +20,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  goal: {
    flag: {
      imageUrl: "images/interactable/flag.png",
      width: 100,
      height: 100,
      hitWidth: 100,
      hitHeight: 100,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: 0,
      contactScoreChange: +100,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  platform: {
    basicPlatform: {
      imageUrl: "images/interactable/basic-platform.png",
      width: 200,
      height: 50,
      hitWidth: 200,
      hitHeight: 50,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 50,
      contactHealthChange: 0,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: Infinity,
      collect: false,
    },
  },
};
// === END DEFAULT VALUES ===
